export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCESS = 'USER_SIGNIN_SUCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCESS = 'USER_SIGNUP_SUCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';
